---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodejs-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-tutorial.labels" . | nindent 4 }}
    {{- if .Values.nodejsconfig.labels }}
    {{- toYaml .Values.nodejsconfig.labels | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "helm-tutorial.labels" . | nindent 4 }}
    {{- if .Values.nodejsconfig.labels }}
    {{- toYaml .Values.nodejsconfig.labels | nindent 4 }}
    {{- end }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.nodejsconfig.port }}
