name: Update the chart with the latest docker Image tag

on:
  push:
    branches:
      - main
      # - 'feat/*'
  pull_request:
    branches:
      - main
permissions:
  contents: write

jobs:
  update-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Helm Repository
        uses: actions/checkout@v4

      - name: Set Docker Image Tag
        run: |
          echo "IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:${{ github.head_ref || github.ref_name }}-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Update the helm chart with the latest tag
        run: |
          ls -Rl
          sed -i "/nodejsconfig:/,/image:/s|image:.*|image: ${IMAGE_TAG}|" ./nodejs-application/values.yaml
          grep -A 1 "nodejsconfig:" nodejs-application/values.yaml

        if: github.event_name == 'push'
      - name: Commit and push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@github.com"
          git add nodejs-application/values.yaml
          git commit -m "Update Docker image ${IMAGE_TAG} tag in values.yml"
          git push origin ${GITHUB_REF#refs/heads/}

        if: github.event_name == 'pull_request'
      - name: Commit and push Changes
        run: |
          git checkout ${{ github.head_ref }}
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@github.com"
          git add nodejs-application/values.yaml
          git commit -m "Update Docker image ${IMAGE_TAG} tag in values.yml"
          git push origin ${{ github.head_ref || github.ref_name }}
